using System.ComponentModel.DataAnnotations;

namespace se347_be.Work.DTOs.Quiz
{
    public class CreateQuizDTO
    {
        [Required(ErrorMessage = "Title is required")]
        [StringLength(255)]
        public string Title { get; set; } = "";

        [StringLength(255)]
        public string? Description { get; set; }

        public DateTime? StartTime { get; set; }

        public DateTime? DueTime { get; set; }

        public int MaxTimesCanAttempt { get; set; } = 1;

        public bool IsPublish { get; set; } = false;

        public bool IsShuffleAnswers { get; set; } = false;

        public bool IsShuffleQuestions { get; set; } = false;

        public int? DurationInMinutes { get; set; }

        // AccessCode will be auto-generated by system (6 random characters)
        // Use PUT /reset-access-code to change it later

        public bool ShowScoreAfterSubmission { get; set; } = false;

        public bool SendResultEmail { get; set; } = false;

        [StringLength(20)]
        public string ShowCorrectAnswersMode { get; set; } = "Never"; // "Never", "Immediately", "AfterDueTime"

        public bool AllowNavigationBack { get; set; } = true;

        [StringLength(20)]
        public string PresentationMode { get; set; } = "AllAtOnce"; // "AllAtOnce", "OneByOne"

        [StringLength(20)]
        public string ScoringMode { get; set; } = "Standard"; // "Standard" (equal points), "Flexible" (custom points per question)
    }
}
